### PR TITLE
Addition of variables to Ntuple

### PR DESCRIPTION
**Pull request by lceard**
added run,event and lumisection to Ntuple
added isolation variables for electron and photon to Ntuple
added ma variable to Diphoton candidate to Ntuple

### CODE REVIEW

**Comment by lceard** [comment]
Hi @youyingli : these are the addition of the variables to the Ntuple that we have discussed.
Please have a look if you think that some other variables should be added. Or if you think that some additions are not useful.

**Comment by youyingli** [comment]
> Hi @youyingli : these are the addition of the variables to the Ntuple that we have discussed.
> Please have a look if you think that some other variables should be added. Or if you think that some additions are not useful.

Hi @lceard : 

- Does this analysis use PV (0th vertex) as the Higgs vertex ? If true,

dipho_mva0       
dipho_mva2              
dipho_dZ1               
dipho_dZ2              
dipho_vtxProbMVA

might be useless because this is for the technical variables of vertex identification.

- Does the analysis also want to use these photon ISO? For the photon ISO, photon ID MVA training includes some ISO like 

https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/MicroAOD/src/PhotonIdUtils.cc#L224-L226

so using photon ID MVA is significant?

**Comment by lceard** [comment]
Thanks for the comments You-Ying.


On Fri, 2 Aug 2019 at 06:19, You-Ying Li <notifications@github.com> wrote:

> Hi @youyingli <https://github.com/youyingli> : these are the addition of
> the variables to the Ntuple that we have discussed.
> Please have a look if you think that some other variables should be added.
> Or if you think that some additions are not useful.
>
> Hi @lceard <https://github.com/lceard> :
>
>    - Does this analysis use PV (0th vertex) as the Higgs vertex ? If true,
>
> dipho_mva0
> dipho_mva2
> dipho_dZ1
> dipho_dZ2
> dipho_vtxProbMVA
>
> might be useless because this is for the technical variables of vertex
> identification.
>
I thought these variables were also used in the Isolation.
Kirill do you have an idea about it?


>
>    - Does the analysis also want to use these photon ISO? For the photon
>    ISO, photon ID MVA training includes some ISO like
>
>
> https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/MicroAOD/src/PhotonIdUtils.cc#L224-L226
>
> so using photon ID MVA is significant?
>
> —
>
Yes I think it is a good idea to add them.
Kirill can you confirm?

Thanks!

Ludivine

**Comment by lceard** [comment]
Hi Ludivine, All,

> Le 2 août 2019 à 17:04, Ludivine Ceard <ludivine.ceard@cern.ch> a écrit :
> 
> Thanks for the comments You-Ying.
> 
> 
> On Fri, 2 Aug 2019 at 06:19, You-Ying Li <notifications@github.com <mailto:notifications@github.com>> wrote:
> Hi @youyingli <https://github.com/youyingli> : these are the addition of the variables to the Ntuple that we have discussed.
> Please have a look if you think that some other variables should be added. Or if you think that some additions are not useful.
> 
> Hi @lceard <https://github.com/lceard> :
> 
> Does this analysis use PV (0th vertex) as the Higgs vertex ? If true,
> dipho_mva0
> dipho_mva2
> dipho_dZ1
> dipho_dZ2
> dipho_vtxProbMVA
> 
> might be useless because this is for the technical variables of vertex identification.
> 
> I thought these variables were also used in the Isolation.
> Kirill do you have an idea about it?

I don’t recall the specific variables that are using the isolation, but the variables listed above (e.g. dZ) seem to refer to longitudinal impact parameter and are not related to isolation.
As our current code only considers the zero vertex, we should probably avoid adding these variables - unless we decide to store all vertices.

>  
> Does the analysis also want to use these photon ISO? For the photon ISO, photon ID MVA training includes some ISO like
> https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/MicroAOD/src/PhotonIdUtils.cc#L224-L226 <https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/MicroAOD/src/PhotonIdUtils.cc#L224-L226>
> so using photon ID MVA is significant?
> 
> —
> 
> Yes I think it is a good idea to add them.
> Kirill can you confirm?

Yes, I would vote for it too.

Thanks,

Kirill

**Pull request closed without merging**
